### Apk
alias apka='apk add'
alias apkacsg='apk add cosign'
alias apkd='apk del'
alias apkl='apk list'
alias apki='apk info'
alias apkud='apk update'
alias apkug='apk upgrade'
alias apkf='apk fetch'
alias apkc='apk cache'
alias apks='apk search'
