### Pip command [ Python package manager ]
alias pil='pip list'
alias pif='pip freeze'
alias pi='pip install'
alias pir='pip install -r'
alias pirr='pip install -r requirements.txt'
alias pirrt='pip install -r requirements.txt --target'
alias pians='pip install ansible'
alias pipyg='pip install pygments'
alias pidggsdk='pip install dagger-io'
alias pis3='pip install s3cmd'
alias pisn='pip install snowflake-cli'
alias pifl8='python -m pip install flake8'
alias pirgr='pip install ranger-fm'
alias pinp='pip install numpy'
alias pipd='pip install pandas'
alias pimpl='pip install matplotlib'
alias pipag='pip install pyautogit'
alias pippy='pip install pyyaml'
alias pijson='pip install json'
alias piconan='pip install conan'
alias pit2r='pip install toml-to-requirements'
alias pipt='pip install pytorch'
alias pitsf='pip install tensorflow'
alias pisp='pip install sympy'
alias pigs='pip install gensim'
alias piscikit='pip install scikit-learn'
alias pigv='pip install graphviz'
alias pidgr='pip install diagrams'

### Pip3
alias pi3='pip3'
alias pi3i='pip3 install'
alias pi3ive='pip3 install virtualenv'
