# Yum
alias yi='yum install -y'
alias yu='yum update -y'
alias yyu='yi yum-utils'
alias yepel='yi epel-release'

alias ysl='yum --showduplicate list'
alias yslk='sudo yum list --showduplicates kubeadm --disableexcludes=kubernetes'
alias ygl='yum group list'
alias ignome='yum groupinstall "Server with GUI" -y ; systemctl set-default graphical ; reboot'

alias ysm='yi subscription-manager'
alias yrgr='yepel; yi ranger'
alias ymat='yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo'
alias ymagh='yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo'
alias yma='yum-config-manager --add-repo'
alias yme='yum-config-manager --enable'
alias ynv='yum install -y neovim'
alias yt='yum install terraform -y'
alias yrsync='yum install rsync -y'
alias yterra='yyu;ymat;yt'
alias ytm='yum install tmux -y'
alias ydbg='yum install dbg -y'
alias ycr='yum install cronie -y'
alias yier='yum install epel-release -y'
alias ymysqlsv='yum install mysql-server'
alias ywg='yum install wget -y'
alias ycu='yum install curl -y'
alias ylz4='yum install lz4 -y'
alias yem='yum install emacs -y'
alias yd='yum install docker -y'
alias ysshfs='yum install sshfs -y' # sshfs username@remote_server:/path/to/remote/directory ~/remote_mount
alias ylib='yum -y install pkgconfig automake gcc zlib-devel pcre-devel xz-devel'
alias ylib3='yum -y install gcc gcc-c++ gmp gmp-devel make ncurses ncurses-compat-libs xz perl'
alias ytool='yum -y groupinstall "Development Tools"'
alias ybu='yum -y install bind-utils'
alias yn='yum install nodejs -y'
alias ynpm='yum install npm -y'
alias yg='yum install git -y'
alias yr='yum remove -y'
alias yu='yum update -y'
alias ygi='yum groupinstall -y'
alias ygr='yum groupremove -y'
alias ygu='yum groupupdate -y'
alias ygcc='yi gcc'
alias ymaria='yum install -y mariadb105'
