#!/bin/bash

LOCAL_IPADDRESS=${1}
REMOTE_PORT=${2}
REMOTE_IPADDRESS=${3}
LOCAL_PORT=${4}
BASTION_HOST=${5}

if [[ -z ${BASTION_HOST} ]]; then
  ssh -NCL ${LOCAL_IPADDRESS}:${LOCAL_PORT}:${REMOTE_IPADDRESS}:${REMOTE_PORT}
else
  ssh -NCL ${LOCAL_IPADDRESS}:${LOCAL_PORT}:${REMOTE_IPADDRESS}:${REMOTE_PORT} ${BASTION_HOST}
fi
