### SYSTEMCTL
alias stcstp='systemctl stop'
alias stcen='systemctl enable'
alias stced='systemctl edit'
alias stcstt='systemctl start'
alias stcrst='systemctl restart'
alias stcrld='systemctl daemon-reload'
alias stcsts='systemctl status'
alias stcsh='systemctl show'
alias stcdis='systemctl disable'
alias stcia='systemctl is-active'
alias stccat='systemctl cat'
alias stcluts='systemctl list-units --type=service'
alias stclr='systemctl list-units --type=service --state=running'
alias stclfr='systemctl list-unit-files --type=service --state=running'
alias secr='systemctl enable crond'
alias sscr='systemctl start crond'
