### [Dotnet]
alias dntap='dotnet add package'
alias dntrp='dotnet remove package'
alias dntnc='dotnet new console'
alias dntnw='dotnet new web'
alias dntnwapi='dotnet new webapi'
alias dntrs='dotnet restore'
alias dntb='dotnet build'
alias dntr='dotnet run'
alias dntt='dotnet test'
