### Go
alias gor='go run'
alias gom='go mod'
alias gomv='go mod vendor'
alias gomi='go mod init'
alias gomt='go mod tidy'
alias gomtu='go mod tidy -u'
alias gome='go mod edit'
alias gomer='go mod edit -require'
alias gomerr='go mod edit -require -remove'
alias gomerp='go mod edit -replace'
alias gob='go build'
alias gobo='go build -o'
alias goe='go env'
alias goep='go env GOPATH'
alias goi='go install'
alias gog='go get'
alias goa='. $HOME/bash/core/script/goa.sh'
