### Azure command
alias azlg='az login'
alias azlgudc='az login --use-device-code'
alias azaccl='az account list'
alias azaccc='az account create'
alias aznwl='az network watcher list'
alias aznwls='az network watcher list --subscription'
alias aznwld='az network watcher delete'
alias azgrl='az group list'
alias azgrc='az group create'
alias azaccss='az account set - subscription'
alias azaccs='az account show'
alias azaccscrl='az account subscription list'
alias azrbac='. $HOME/preconfig/Suitcase/bash/scripts/azureRBAC.sh'
alias azaccsctl='az account subscription list'
alias azaccscte='az account subscription enable'
alias azaccscts='az account subscription show'
alias azaccsctr='az account subscription rename'
alias azgrl='az group list'
alias azgrs='az group show'
alias azgru='az group update'
alias azgrw='az group wait'
alias azgrd='az group delete -n'
alias azgrdpm='az group deployment'
alias aznwvnl='az network vnet list'
alias azaksl='az aks list'
alias azaksgc='az aks get-credentials'
alias azaksgcc='. $HOME/preconfig/Suitcase/bash/scripts/azureGetCredentials.sh'
alias azaksd='az aks delete'
alias azaksc='az aks create'
alias azakss='az aks show'
alias azaksu='az aks update'
alias azaksuc='az aks update-credentials'
alias azakssc='az aks scale'
alias azaksstt='az aks start'
alias azaksstp='az aks stop'
alias azacrb='az acr build'
alias azacrc='az acr create'
alias azacrl='az acr list'
alias azacrs='az acr show'
alias azacrlg='az acr login'
alias azacru='az acr update'
alias azacrr='az acr run'
alias azacrq='az acr query'
alias azacri='az acr import'
alias azacrch='az acr check-health'
alias azacrcn='az acr check-name'

### AzureCopy command
alias azcplg='azcopy login'
alias azcpcp='azcopy copy'
alias azcpls='azcopy ls'


