# linux
source "$(dirname "${BASH_SOURCE[0]}")/linux/basic.sh"
source "$(dirname "${BASH_SOURCE[0]}")/linux/su.sh"
source "$(dirname "${BASH_SOURCE[0]}")/linux/cd.sh"
source "$(dirname "${BASH_SOURCE[0]}")/linux/rm.sh"
source "$(dirname "${BASH_SOURCE[0]}")/linux/cat.sh"
source "$(dirname "${BASH_SOURCE[0]}")/linux/ssh.sh"
source "$(dirname "${BASH_SOURCE[0]}")/linux/cron.sh"
source "$(dirname "${BASH_SOURCE[0]}")/linux/ufw.sh"
source "$(dirname "${BASH_SOURCE[0]}")/linux/chmod.sh"
source "$(dirname "${BASH_SOURCE[0]}")/linux/iptables.sh"
source "$(dirname "${BASH_SOURCE[0]}")/linux/systemctl.sh"
source "$(dirname "${BASH_SOURCE[0]}")/linux/journalctl.sh"
