### Trivy
alias t1='trivy'
alias t1i='trivy image'
alias t1r='trivy repo'
alias t1fs='trivy fs'
alias t1c='trivy client'
alias t1s='trivy server'
alias t1k='trivy k8s'
alias tv='trivy'
alias tvi='trivy image'
alias tvr='trivy repo'
alias tvfs='trivy fs'
alias tvc='trivy client'
alias tvs='trivy server'
alias tvk='trivy k8s'
