[org]
blockchain = [
  # Bitcoin
  "https://github.com/dappuniversity",

  "https://github.com/dappuniversity",
  "https://github.com/ccxt",
  "https://github.com/decentrio",
  "https://github.com/orbitorg",
  "https://github.com/aura-nw",
  "https://github.com/ark-us",
  "https://github.com/envoylabs/",

  "https://github.com/paritytech",

  # Cosmos
  "https://github.com/cosmos/awesome-cosmos",
  "https://github.com/cosmos",
  "https://github.com/CosmWasm",
  "https://github.com/confio",
  "https://github.com/hyperweb-io",
  "https://github.com/informalsystems",
  "https://github.com/firmachain",
  "https://github.com/crypto-org-chain",
  "https://github.com/noble-assets",
  "https://github.com/KiraCore",
  "https://github.com/Team-Kujira",
  "https://github.com/persistenceOne",
  "https://github.com/aragon",
  "https://github.com/e-money",
  "https://github.com/sentinel-official",
  "https://github.com/hyperledger-archives",
  "https://github.com/irisnet/",
  "https://github.com/iov-one",
  "https://github.com/datopia",
  "https://github.com/likecoin",
  "https://github.com/akash-network",
]

ai = ["https://github.com/WasmEdge"]

[user]
blockchain = [
  # Bitcoin
  "https://github.com/kanoi",
  "https://github.com/wareck",
  "https://github.com/luke-jr",

  # Notional Ventures
  "https://github.com/faddat",
  "https://github.com/baabeetaa",
  "https://github.com/TropicalDog17",
  "https://github.com/kien6034",
  "https://github.com/hoank101",
  "https://github.com/minhngoc270499",
  "https://github.com/tungleanh0902",
  "https://github.com/hakuno2000",

  # Hyperlane
  "https://github.com/nambrot",

  # IDK
  "https://github.com/vinhyenvodoi98",
]

[repo]
blockchain = [
  # Bitcoin
  "https://github.com/bitcoin/bitcoin",
  "https://github.com/bitcoin/bips",

  "https://github.com/bitcoin-core/gui",
  "https://github.com/bitcoin-core/secp256k1",
  "https://github.com/bitcoin-core/HWI",

  "https://github.com/bitcoinknots/bitcoin",
  "https://github.com/libbitcoin/libbitcoin-system",
  "https://github.com/btcsuite/btcd",
  "https://github.com/bcoin-org/bcoin",

  "https://github.com/ElementsProject/lightning",
  "https://github.com/lightningnetwork/lnd",
  "https://github.com/ACINQ/eclair",

  "https://github.com/lightninglabs/loop",
  "https://github.com/lightninglabs/pool",

  "https://github.com/spesmilo/electrum",
  "https://github.com/sparrowwallet/sparrow",
  "https://github.com/zkSNACKs/WalletWasabi",
  "https://github.com/BlueWallet/BlueWallet",

  "https://github.com/bitcoinj/bitcoinj",
  "https://github.com/MetacoSA/NBitcoin",
  "https://github.com/bitcoinjs/bitcoinjs-lib",

  "https://github.com/bitcoin-core/secp256k1",
  "https://github.com/bitcoin-core/miniscript",
  "https://github.com/rust-bitcoin/rust-bitcoin",
  "https://github.com/rust-bitcoin/rust-miniscript",

  "https://github.com/romanz/electrs",
  "https://github.com/Blockstream/esplora",
  "https://github.com/cculianu/Fulcrum",
  "https://github.com/dgarage/NBXplorer",

  "https://github.com/mempool/mempool",
  "https://github.com/janoside/btc-rpc-explorer",

  "https://github.com/ckolivas/cgminer",
  "https://github.com/luke-jr/bfgminer",

  "https://github.com/stratum-mining/stratum",
]
