### Terraform command
alias tfcs='. $HOME/bash/core/script/cleanState.sh'
alias tfc='. $HOME/bash/core/script/clean.sh'
alias tfi='terraform init'
alias tfiu='terraform init -upgrade'
alias tfpr='terraform providers'
alias tff='terraform fmt'
alias tfvs='terraform version'
alias tfv='terraform validate'
alias tfs='terraform show'
alias tfg='terraform graph'
alias tfssrm='terraform state rm'
alias tfssvm='terraform state mv'
alias tfo='terraform output'
alias tfojs='terraform output -json > sensitive.json'
alias tfful='terraform force-unlock -force'
alias tfsp='gpgterraform state pull'
alias tfp='terraform plan'
alias tfplf='terraform plan -lock=false'
alias tfim='terraform import' # terraform plan -generate-config-out="generated.tf"
alias tfsl='terraform state list'
alias tfss='terraform state show'
alias tflg='terraform login'
alias tfrf='terraform refresh'
alias tfrp='terraform replace'
alias tfro='terraform apply -refresh-only'
alias tfa='terraform apply'
alias tfd='terraform destroy'
alias tfdpl='terraform destroy'
alias tfwl='terraform workspace list'
alias tfws='terraform workspace select'
alias tfwn='terraform workspace new'
alias tfaa='terraform apply --auto-approve'
alias tfda='terraform destroy --auto-approve'
alias tfiacpt='terraform -chdir=$HOME/preconfig/Suitcase/bash/infra/gcp/compute init ; terraform -chdir=$HOME/preconfig/Suitcase/bash/infra/gcp/compute apply --auto-approve'
alias tfdacpt='terraform -chdir=$HOME/preconfig/Suitcase/bash/infra/gcp/compute destroy --auto-approve'
alias tfiagke='terraform -chdir=$HOME/preconfig/Suitcase/bash/infra/gcp/gke init ; terraform -chdir=$HOME/preconfig/Suitcase/bash/infra/gcp/gke apply --auto-approve'
alias tfdagke='terraform -chdir=$HOME/preconfig/Suitcase/bash/infra/gcp/gke destroy --auto-approve'
alias tfia='tfi ; tfaa'
alias tfid='tfi ; tfda'
alias tfdia='tfda ; tfi ; tfaa'
