### Vagrant command
alias vgv='vagrant version'
alias vgi='vagrant init'
alias vgu='vagrant up'
alias vgd='vagrant destroy'
alias vgh='vagrant halt'
alias vgrl='vagrant reload'
alias vgst='vagrant status'
alias vggst='vagrant global-status'
alias vgsp='vagrant suspend'
alias vgrs='vagrant resume'
alias vgpr='vagrant provision'
alias vgbl='vagrant box list'
alias vgbll='vagrant box list --long'
alias vgssh='vagrant ssh'
alias vgsc='vagrant ssh-config'
alias vgsl='vagrant snapshot list'
alias vgss='vagrant snapshot save'
alias vgsd='vagrant snapshot delete'
alias vgsr='vagrant snapshot restore'
alias vgpli='vagrant plugin install'
alias vgplqm='vagrant plugin install vagrant-qemu'

