### gaiad
alias g4i='gaiad init'
alias g4cf='gaiad config'
alias g4s='gaiad start'
alias g4e='gaiad export'
alias g4tdmsa='gaiad tendermint show-address'
alias g4kl='gaiad keys list'
alias g4ka='gaiad keys add'
alias g4kd='gaiad keys delete'
alias g4kr='gaiad keys add --recover'
alias g4ksa='gaiad keys show -a'
alias g4tx='gaiad tx'
alias g4txs='gaiad tx send'
alias g4txb='gaiad tx broadcast'
alias g4q='gaiad q'
alias g4qb='gaiad q bank'
alias g4qbb='gaiad q bank balances'
alias g4aga='gaiad add-genesis-account'

